<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="req" nsURI="www.req.com" nsPrefix="req">
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HLR" eSuperTypes="#//Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="llrs" upperBound="-1" eType="#//LLR"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ReqType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LLR" eSuperTypes="#//Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hlrs" upperBound="-1" eType="#//HLR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReqType">
    <eLiterals name="Functional"/>
    <eLiterals name="Safety" value="1"/>
    <eLiterals name="Reliability" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SR" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SSS"/>
</ecore:EPackage>
