<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="www.test.com" nsPrefix="Test">
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="4"
        eType="#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friends" ordered="false"
        upperBound="-1" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sex" eType="#//SEX"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="father" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mother" eType="#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SEX">
    <eLiterals name="MAN"/>
    <eLiterals name="WOMAN" value="1"/>
  </eClassifiers>
</ecore:EPackage>
